-- ============================================
-- Smart Shop — Complete Subscription System
-- Tables: plans, subscriptions, deliveries
-- ============================================

-- ── Subscription Plans (created by vendors) ────────────────
CREATE TABLE IF NOT EXISTS subscription_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  name_amharic TEXT DEFAULT '',
  emoji TEXT DEFAULT '📦',
  description TEXT DEFAULT '',
  category TEXT DEFAULT 'general',
  unit TEXT DEFAULT '1',
  unit_label TEXT DEFAULT 'pc',
  daily_price INTEGER DEFAULT 0,
  weekly_price INTEGER DEFAULT 0,
  monthly_price INTEGER DEFAULT 0,
  vendor_id BIGINT,
  vendor_name TEXT DEFAULT 'Smart Shop',
  image TEXT DEFAULT '',
  tags JSONB DEFAULT '[]'::jsonb,
  is_active BOOLEAN DEFAULT true,
  min_quantity INTEGER DEFAULT 1,
  max_quantity INTEGER DEFAULT 10,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Customer Subscriptions ─────────────────────────────────
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS plan_id BIGINT REFERENCES subscription_plans(id);
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS delivery_time TEXT DEFAULT '07:00';
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'cod';
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS total_delivered INTEGER DEFAULT 0;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS last_delivery TIMESTAMPTZ;

-- ── Subscription Delivery Records ──────────────────────────
CREATE TABLE IF NOT EXISTS subscription_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id BIGINT REFERENCES subscriptions(id) ON DELETE CASCADE,
  plan_id BIGINT REFERENCES subscription_plans(id),
  telegram_id BIGINT,
  product_name TEXT DEFAULT '',
  quantity INTEGER DEFAULT 1,
  price INTEGER DEFAULT 0,
  delivery_address TEXT DEFAULT '',
  delivery_date TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','out_for_delivery','delivered','failed','cancelled')),
  delivered_at TIMESTAMPTZ,
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Seed default plans ─────────────────────────────────────
INSERT INTO subscription_plans (name, name_amharic, emoji, description, category, unit, unit_label, daily_price, weekly_price, monthly_price, tags) VALUES
  ('Fresh Cow Milk', 'የከብት ወተት', '🥛', 'Fresh cow milk delivered every morning', 'dairy', '1', 'liter', 60, 380, 1520, '["popular","essential"]'),
  ('Brown Eggs', 'እንቁላል', '🥚', 'Farm-fresh brown eggs', 'dairy', '6', 'pieces', 0, 150, 560, '["popular"]'),
  ('White Bread', 'ነጭ ዳቦ', '🍞', 'Freshly baked white bread daily', 'bakery', '1', 'loaf', 25, 160, 620, '["essential"]'),
  ('Pure Water 5L', 'ንጹህ ውሃ 5ሊ', '💧', 'Purified drinking water 5L bottle', 'drinks', '1', 'bottle', 40, 260, 1000, '["essential"]'),
  ('Ethiopian Coffee', 'የኢትዮጵያ ቡና', '☕', 'Premium Ethiopian coffee beans 500g', 'groceries', '500', 'gram', 0, 0, 800, '["premium"]'),
  ('Pure Honey', 'ንጹህ ማር', '🍯', 'Pure natural Ethiopian honey 500g', 'groceries', '500', 'gram', 0, 0, 1200, '["premium"]'),
  ('Sugar 1kg', 'ስኳር 1ኪሎ', '🍚', 'White sugar 1kg pack', 'groceries', '1', 'kg', 0, 0, 520, '["essential"]'),
  ('Cooking Oil 1L', 'የምግብ ዘይት 1ሊ', '🫒', 'Vegetable cooking oil 1L', 'groceries', '1', 'liter', 0, 0, 650, '["essential"]')
ON CONFLICT DO NOTHING;

-- ── Indexes ─────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_sp_category ON subscription_plans(category);
CREATE INDEX IF NOT EXISTS idx_sp_active ON subscription_plans(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_subs_plan ON subscriptions(plan_id);
CREATE INDEX IF NOT EXISTS idx_subs_user ON subscriptions(telegram_id);
CREATE INDEX IF NOT EXISTS idx_subs_next ON subscriptions(next_delivery) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_sd_subscription ON subscription_deliveries(subscription_id);
CREATE INDEX IF NOT EXISTS idx_sd_date ON subscription_deliveries(delivery_date);

-- ── RLS Policies ────────────────────────────────────────────
ALTER TABLE subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_deliveries ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'subscription_plans' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON subscription_plans FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'subscription_deliveries' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON subscription_deliveries FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
