-- ============================================
-- Smart Shop — Outstanding Features Migration
-- Group Buying, Gift Registry, Subscriptions, Reseller
-- ============================================

-- ── Group Buying (ማህበር ግዢ) ──────────────────────────────
CREATE TABLE IF NOT EXISTS group_deals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT NOT NULL,
  product_image TEXT DEFAULT '',
  regular_price INTEGER NOT NULL,
  group_price INTEGER NOT NULL,
  min_members INTEGER DEFAULT 2,
  max_members INTEGER DEFAULT 10,
  current_members INTEGER DEFAULT 1,
  creator_telegram_id BIGINT NOT NULL,
  creator_name TEXT DEFAULT '',
  share_token TEXT UNIQUE NOT NULL,
  status TEXT DEFAULT 'open' CHECK (status IN ('open','active','fulfilled','expired')),
  expires_at TIMESTAMPTZ DEFAULT NOW() + INTERVAL '48 hours',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS group_deal_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_deal_id BIGINT REFERENCES group_deals(id) ON DELETE CASCADE,
  telegram_id BIGINT NOT NULL,
  full_name TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  quantity INTEGER DEFAULT 1,
  paid BOOLEAN DEFAULT false,
  joined_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Gift Registry (የሰርግ ስጦታ መዝገብ) ─────────────────────────
CREATE TABLE IF NOT EXISTS gift_registries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  couple_name TEXT NOT NULL,
  couple_amharic_name TEXT DEFAULT '',
  wedding_date TEXT NOT NULL,
  wedding_location TEXT DEFAULT '',
  message TEXT DEFAULT '',
  share_token TEXT UNIQUE NOT NULL,
  creator_telegram_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS registry_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registry_id BIGINT REFERENCES gift_registries(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT NOT NULL,
  product_image TEXT DEFAULT '',
  price INTEGER NOT NULL,
  quantity INTEGER DEFAULT 1,
  purchased INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS registry_purchases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registry_item_id BIGINT REFERENCES registry_items(id) ON DELETE CASCADE,
  buyer_name TEXT NOT NULL,
  buyer_telegram_id BIGINT,
  quantity INTEGER DEFAULT 1,
  amount INTEGER NOT NULL,
  message TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Subscriptions (የደንበኝነት ምርቶች) ─────────────────────────
CREATE TABLE IF NOT EXISTS subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id BIGINT NOT NULL,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT NOT NULL,
  product_image TEXT DEFAULT '',
  quantity INTEGER DEFAULT 1,
  frequency TEXT NOT NULL CHECK (frequency IN ('daily','weekly','monthly')),
  price INTEGER NOT NULL,
  next_delivery TIMESTAMPTZ NOT NULL,
  status TEXT DEFAULT 'active' CHECK (status IN ('active','paused','cancelled')),
  delivery_address TEXT DEFAULT '',
  delivery_note TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Reseller Program ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS referral_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_telegram_id BIGINT NOT NULL,
  referral_code TEXT NOT NULL,
  referred_telegram_id BIGINT,
  product_id BIGINT,
  order_number TEXT,
  amount INTEGER DEFAULT 0,
  commission INTEGER DEFAULT 0,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','paid','cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Photo Reviews Enhancement (adds to existing reviews table) ─
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS images JSONB DEFAULT '[]'::jsonb;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS telegram_id BIGINT;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT false;

-- ── Indexes ──────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_gd_status ON group_deals(status);
CREATE INDEX IF NOT EXISTS idx_gd_share ON group_deals(share_token);
CREATE INDEX IF NOT EXISTS idx_gd_product ON group_deals(product_id);
CREATE INDEX IF NOT EXISTS idx_gdm_deal ON group_deal_members(group_deal_id);
CREATE INDEX IF NOT EXISTS idx_gr_share ON gift_registries(share_token);
CREATE INDEX IF NOT EXISTS idx_ri_registry ON registry_items(registry_id);
CREATE INDEX IF NOT EXISTS idx_subs_user ON subscriptions(telegram_id);
CREATE INDEX IF NOT EXISTS idx_subs_next ON subscriptions(next_delivery) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_rl_referrer ON referral_logs(referrer_telegram_id);
CREATE INDEX IF NOT EXISTS idx_rl_code ON referral_logs(referral_code);

-- ── RLS Policies ────────────────────────────────────────────
ALTER TABLE group_deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE group_deal_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE gift_registries ENABLE ROW LEVEL SECURITY;
ALTER TABLE registry_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE registry_purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE referral_logs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'group_deals' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON group_deals FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'group_deal_members' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON group_deal_members FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'gift_registries' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON gift_registries FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'registry_items' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON registry_items FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'registry_purchases' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON registry_purchases FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'subscriptions' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON subscriptions FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'referral_logs' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON referral_logs FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
