-- ============================================
-- Smart Shop — Admin Features Tables Migration
-- Date: 2026-07-26
-- Run this in Supabase SQL Editor AFTER the delivery migration
-- ============================================

-- ── Manual Payments ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS manual_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT,
  amount INTEGER NOT NULL,
  payment_method TEXT DEFAULT 'bank' CHECK (payment_method IN ('bank','telebirr','chapa','cash')),
  bank_name TEXT DEFAULT '',
  account_name TEXT DEFAULT '',
  account_number TEXT DEFAULT '',
  transaction_id TEXT DEFAULT '',
  receipt_url TEXT DEFAULT '',
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','verified','rejected','refunded')),
  verified_by BIGINT,
  verified_at TIMESTAMPTZ,
  customer_telegram_id BIGINT,
  customer_name TEXT DEFAULT '',
  customer_phone TEXT DEFAULT '',
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Bank Accounts (for manual payments) ────────────────────────────
CREATE TABLE IF NOT EXISTS bank_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bank_name TEXT NOT NULL,
  account_name TEXT NOT NULL,
  account_number TEXT NOT NULL,
  branch TEXT DEFAULT '',
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Vendor Payouts ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id BIGINT,
  vendor_name TEXT DEFAULT '',
  amount INTEGER NOT NULL,
  commission_deducted INTEGER DEFAULT 0,
  payment_method TEXT DEFAULT 'telebirr' CHECK (payment_method IN ('bank','telebirr','chapa')),
  account_name TEXT DEFAULT '',
  account_number TEXT DEFAULT '',
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','processing','paid','failed','cancelled')),
  period_start TIMESTAMPTZ,
  period_end TIMESTAMPTZ,
  paid_at TIMESTAMPTZ,
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Returns / Refunds ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS returns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT NOT NULL,
  product_id BIGINT,
  product_name TEXT DEFAULT '',
  quantity INTEGER DEFAULT 1,
  reason TEXT DEFAULT '',
  description TEXT DEFAULT '',
  images JSONB DEFAULT '[]'::jsonb,
  refund_amount INTEGER DEFAULT 0,
  refund_method TEXT DEFAULT 'original' CHECK (refund_method IN ('original','bank','telebirr','store_credit')),
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','refunded','completed')),
  customer_telegram_id BIGINT,
  customer_name TEXT DEFAULT '',
  customer_phone TEXT DEFAULT '',
  approved_by BIGINT,
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Order Fulfillments ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS order_fulfillments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','processing','packed','shipped','delivered','cancelled')),
  items JSONB DEFAULT '[]'::jsonb,
  tracking_code TEXT DEFAULT '',
  carrier TEXT DEFAULT '',
  notes TEXT DEFAULT '',
  packed_by BIGINT,
  packed_at TIMESTAMPTZ,
  shipped_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Abandoned Carts ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS abandoned_carts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id BIGINT,
  customer_name TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  items JSONB DEFAULT '[]'::jsonb,
  total INTEGER DEFAULT 0,
  recovery_status TEXT DEFAULT 'new' CHECK (recovery_status IN ('new','contacted','recovered','lost')),
  recovery_message_id BIGINT,
  recovered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Coupon Usage Analytics ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS coupon_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coupon_code TEXT NOT NULL,
  discount_amount INTEGER DEFAULT 0,
  order_number TEXT,
  customer_telegram_id BIGINT,
  customer_name TEXT DEFAULT '',
  used_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Admin Roles ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS admin_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  permissions JSONB DEFAULT '[]'::jsonb,
  description TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id BIGINT UNIQUE,
  username TEXT DEFAULT '',
  role_id BIGINT REFERENCES admin_roles(id),
  permissions JSONB DEFAULT '[]'::jsonb,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Activity Log ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  entity_type TEXT DEFAULT '',
  entity_id TEXT DEFAULT '',
  admin_id BIGINT,
  admin_name TEXT DEFAULT '',
  details JSONB DEFAULT '{}'::jsonb,
  ip_address TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Accounting / Audit Trail ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS accounting_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_type TEXT NOT NULL CHECK (entry_type IN ('revenue','expense','commission','payout','refund','adjustment')),
  description TEXT DEFAULT '',
  amount INTEGER NOT NULL,
  balance_before INTEGER DEFAULT 0,
  balance_after INTEGER DEFAULT 0,
  reference_type TEXT DEFAULT '',
  reference_id TEXT DEFAULT '',
  created_by BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Promotions ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS promotions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT DEFAULT 'percentage' CHECK (type IN ('percentage','fixed','bogo','free_shipping')),
  value INTEGER DEFAULT 0,
  min_order INTEGER DEFAULT 0,
  max_discount INTEGER DEFAULT 0,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  usage_limit INTEGER DEFAULT 0,
  used_count INTEGER DEFAULT 0,
  applicable_products JSONB DEFAULT '[]'::jsonb,
  applicable_categories JSONB DEFAULT '[]'::jsonb,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── SLA Config ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sla_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  metric TEXT DEFAULT '',
  threshold_minutes INTEGER DEFAULT 30,
  warning_minutes INTEGER DEFAULT 25,
  escalation_minutes INTEGER DEFAULT 60,
  notify_roles JSONB DEFAULT '["admin"]'::jsonb,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sla_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sla_config_id BIGINT REFERENCES sla_config(id),
  entity_type TEXT DEFAULT '',
  entity_id TEXT DEFAULT '',
  status TEXT DEFAULT 'open' CHECK (status IN ('open','acknowledged','resolved')),
  acknowledged_by BIGINT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Notifications (persistent) ─────────────────────────────────────
-- Table already exists from first migration, adding indexes
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_telegram ON notifications(telegram_id);
CREATE INDEX IF NOT EXISTS idx_notifications_read ON notifications(read) WHERE read = false;

-- ── Indexes for new tables ─────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_mp_status ON manual_payments(status);
CREATE INDEX IF NOT EXISTS idx_mp_order ON manual_payments(order_number);
CREATE INDEX IF NOT EXISTS idx_payouts_status ON payouts(status);
CREATE INDEX IF NOT EXISTS idx_payouts_vendor ON payouts(vendor_id);
CREATE INDEX IF NOT EXISTS idx_returns_order ON returns(order_number);
CREATE INDEX IF NOT EXISTS idx_returns_status ON returns(status);
CREATE INDEX IF NOT EXISTS idx_of_order ON order_fulfillments(order_number);
CREATE INDEX IF NOT EXISTS idx_ac_status ON abandoned_carts(recovery_status);
CREATE INDEX IF NOT EXISTS idx_ca_coupon ON coupon_analytics(coupon_code);
CREATE INDEX IF NOT EXISTS idx_al_action ON activity_logs(action);
CREATE INDEX IF NOT EXISTS idx_al_created ON activity_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_ae_type ON accounting_entries(entry_type);
CREATE INDEX IF NOT EXISTS idx_ae_created ON accounting_entries(created_at);
CREATE INDEX IF NOT EXISTS idx_promotions_active ON promotions(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_sla_status ON sla_alerts(status);

-- RLS Policies for new tables
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'manual_payments' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON manual_payments FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'bank_accounts' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON bank_accounts FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'payouts' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON payouts FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'returns' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON returns FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'order_fulfillments' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON order_fulfillments FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'abandoned_carts' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON abandoned_carts FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'coupon_analytics' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON coupon_analytics FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'admin_roles' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON admin_roles FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'admin_users' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON admin_users FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'activity_logs' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON activity_logs FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'accounting_entries' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON accounting_entries FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'promotions' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON promotions FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sla_config' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON sla_config FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sla_alerts' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON sla_alerts FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'delivery_personnel' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON delivery_personnel FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'deliveries' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON deliveries FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'delivery_zones' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON delivery_zones FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'driver_earnings' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON driver_earnings FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'delivery_messages' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON delivery_messages FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

ALTER TABLE manual_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE bank_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE payouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE returns ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_fulfillments ENABLE ROW LEVEL SECURITY;
ALTER TABLE abandoned_carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE coupon_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE accounting_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE sla_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE sla_alerts ENABLE ROW LEVEL SECURITY;

-- Delivery tables RLS (in case not done)
ALTER TABLE delivery_personnel ENABLE ROW LEVEL SECURITY;
ALTER TABLE deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE driver_earnings ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_messages ENABLE ROW LEVEL SECURITY;

NOTIFY pgrst, 'reload schema';
