-- ============================================
-- Smart Shop — Complete Subscription System
-- Run this in Supabase SQL Editor
-- Tables: subscription_plans, subscriptions (enhanced), subscription_deliveries
-- ============================================

-- ── 1. Subscription Plans (created by vendors) ─────────────
CREATE TABLE IF NOT EXISTS subscription_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  name_amharic TEXT DEFAULT '',
  emoji TEXT DEFAULT '📦',
  description TEXT DEFAULT '',
  category TEXT DEFAULT 'general',
  unit TEXT DEFAULT '1',
  unit_label TEXT DEFAULT 'pc',
  daily_price INTEGER DEFAULT 0,
  weekly_price INTEGER DEFAULT 0,
  monthly_price INTEGER DEFAULT 0,
  vendor_id BIGINT,
  vendor_name TEXT DEFAULT 'Smart Shop',
  image TEXT DEFAULT '',
  tags JSONB DEFAULT '[]'::jsonb,
  is_active BOOLEAN DEFAULT true,
  min_quantity INTEGER DEFAULT 1,
  max_quantity INTEGER DEFAULT 10,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 2. Enhance existing subscriptions table ────────────────
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS plan_id BIGINT REFERENCES subscription_plans(id);
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS delivery_time TEXT DEFAULT '07:00';
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS delivery_time_label TEXT DEFAULT 'Morning (7:00-9:00)';
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'cod';
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS total_delivered INTEGER DEFAULT 0;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS total_spent INTEGER DEFAULT 0;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS last_delivery TIMESTAMPTZ;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS next_delivery TIMESTAMPTZ;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS delivery_notes TEXT DEFAULT '';

-- ── 3. Subscription Delivery Records ───────────────────────
CREATE TABLE IF NOT EXISTS subscription_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id BIGINT REFERENCES subscriptions(id) ON DELETE CASCADE,
  plan_id BIGINT REFERENCES subscription_plans(id),
  telegram_id BIGINT,
  product_name TEXT DEFAULT '',
  quantity INTEGER DEFAULT 1,
  price INTEGER DEFAULT 0,
  delivery_address TEXT DEFAULT '',
  delivery_date TEXT,
  delivery_time TEXT DEFAULT '07:00',
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','confirmed','preparing','out_for_delivery','delivered','failed','cancelled')),
  delivered_at TIMESTAMPTZ,
  driver_id BIGINT,
  driver_name TEXT DEFAULT '',
  notes TEXT DEFAULT '',
  rating INTEGER CHECK (rating BETWEEN 1 AND 5),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 4. Seed default subscription plans ─────────────────────
INSERT INTO subscription_plans (name, name_amharic, emoji, description, category, unit, unit_label, daily_price, weekly_price, monthly_price, tags) VALUES
  ('Fresh Cow Milk', 'የከብት ወተት', '🥛', 'Fresh cow milk delivered every morning', 'dairy', '1', 'liter', 60, 380, 1520, '["popular","essential"]'),
  ('Brown Eggs (6pcs)', 'እንቁላል (6ቱ)', '🥚', 'Farm-fresh brown eggs from free-range chickens', 'dairy', '6', 'pieces', 0, 150, 560, '["popular"]'),
  ('White Bread', 'ነጭ ዳቦ', '🍞', 'Freshly baked white bread from local bakery', 'bakery', '1', 'loaf', 25, 160, 620, '["essential"]'),
  ('Pure Water 5L', 'ንጹህ ውሃ 5ሊ', '💧', 'Purified drinking water in reusable 5L bottle', 'drinks', '1', 'bottle', 40, 260, 1000, '["essential"]'),
  ('Ethiopian Coffee 500g', 'የኢትዮጵያ ቡና 500ግ', '☕', 'Premium single-origin Ethiopian coffee beans', 'groceries', '500', 'gram', 0, 0, 800, '["premium"]'),
  ('Pure Honey 500g', 'ንጹህ ማር 500ግ', '🍯', 'Pure natural Ethiopian white honey', 'groceries', '500', 'gram', 0, 0, 1200, '["premium"]'),
  ('White Sugar 1kg', 'ስኳር 1ኪሎ', '🍚', 'Refined white sugar 1kg pack', 'groceries', '1', 'kg', 0, 0, 520, '["essential"]'),
  ('Cooking Oil 1L', 'የምግብ ዘይት 1ሊ', '🫒', 'Premium vegetable cooking oil 1 liter', 'groceries', '1', 'liter', 0, 0, 650, '["essential"]'),
  ('Injera (10pcs)', 'እንጀራ (10ቱ)', '🫓', 'Traditional Ethiopian injera, 10 pieces per pack', 'bakery', '10', 'pieces', 0, 180, 680, '["popular"]'),
  ('Tomato 1kg', 'ቲማቲም 1ኪሎ', '🍅', 'Fresh ripe tomatoes sourced from local farms', 'groceries', '1', 'kg', 0, 0, 180, '[]'),
  ('Onion 1kg', 'ሽንኩርት 1ኪሎ', '🧅', 'Fresh red onions from local market', 'groceries', '1', 'kg', 0, 0, 120, '["essential"]'),
  ('Spice Mix (Berbere)', 'በርበሬ', '🌶️', 'Traditional Ethiopian berbere spice mix 250g', 'groceries', '250', 'gram', 0, 0, 350, '[]')
ON CONFLICT DO NOTHING;

-- ── 5. Update existing subscriptions with next_delivery if null ──
UPDATE subscriptions SET next_delivery = NOW() + INTERVAL '1 day' WHERE next_delivery IS NULL;

-- ── 6. RPC Function: Process daily subscriptions ──────────
CREATE OR REPLACE FUNCTION process_daily_subscriptions()
RETURNS INTEGER AS $$
DECLARE
  processed INTEGER := 0;
  sub_rec RECORD;
  next_date TIMESTAMPTZ;
BEGIN
  FOR sub_rec IN
    SELECT s.*, sp.name as plan_name, sp.emoji
    FROM subscriptions s
    LEFT JOIN subscription_plans sp ON s.plan_id = sp.id
    WHERE s.status = 'active'
    AND s.next_delivery <= NOW()
    LIMIT 50
  LOOP
    -- Create delivery record
    INSERT INTO subscription_deliveries (
      subscription_id, plan_id, telegram_id,
      product_name, quantity, price,
      delivery_address, delivery_date, delivery_time,
      status
    ) VALUES (
      sub_rec.id, sub_rec.plan_id, sub_rec.telegram_id,
      COALESCE(sub_rec.plan_name, sub_rec.product_name),
      sub_rec.quantity, sub_rec.price,
      sub_rec.delivery_address,
      CURRENT_DATE::TEXT,
      sub_rec.delivery_time,
      'pending'
    );
    
    -- Calculate next delivery
    next_date := NOW();
    IF sub_rec.frequency = 'daily' THEN
      next_date := next_date + INTERVAL '1 day';
    ELSIF sub_rec.frequency = 'weekly' THEN
      next_date := next_date + INTERVAL '7 days';
    ELSE
      next_date := next_date + INTERVAL '1 month';
    END IF;
    
    -- Update subscription
    UPDATE subscriptions SET
      next_delivery = next_date,
      last_delivery = NOW(),
      total_delivered = COALESCE(total_delivered, 0) + 1,
      total_spent = COALESCE(total_spent, 0) + sub_rec.price
    WHERE id = sub_rec.id;
    
    processed := processed + 1;
  END LOOP;
  
  RETURN processed;
END;
$$ LANGUAGE plpgsql;

-- ── 7. Indexes for performance ────────────────────────────
CREATE INDEX IF NOT EXISTS idx_sp_category ON subscription_plans(category);
CREATE INDEX IF NOT EXISTS idx_sp_active ON subscription_plans(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_subs_plan ON subscriptions(plan_id);
CREATE INDEX IF NOT EXISTS idx_subs_user ON subscriptions(telegram_id);
CREATE INDEX IF NOT EXISTS idx_subs_next ON subscriptions(next_delivery) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_subs_status ON subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_sd_subscription ON subscription_deliveries(subscription_id);
CREATE INDEX IF NOT EXISTS idx_sd_date ON subscription_deliveries(delivery_date);
CREATE INDEX IF NOT EXISTS idx_sd_status ON subscription_deliveries(status);

-- ── 8. RLS Policies (public access for service_role) ──────
ALTER TABLE IF EXISTS subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS subscription_deliveries ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'subscription_plans' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON subscription_plans FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'subscription_deliveries' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON subscription_deliveries FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'subscriptions' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON subscriptions FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
