-- ============================================
-- Smart Shop — Premium Features Migration
-- Group Buying, Gift Registry, Subscriptions, 
-- Reseller, Price Compare, Photo Reviews
-- ============================================

-- ── Group Deals (ማህበር ግዢ) ──────────────────
CREATE TABLE IF NOT EXISTS group_deals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT NOT NULL,
  product_image TEXT DEFAULT '',
  regular_price INTEGER NOT NULL,
  group_price INTEGER NOT NULL,
  min_members INTEGER DEFAULT 2,
  max_members INTEGER DEFAULT 10,
  current_members INTEGER DEFAULT 1,
  creator_telegram_id BIGINT NOT NULL,
  share_token TEXT UNIQUE NOT NULL DEFAULT '',
  status TEXT DEFAULT 'open' CHECK (status IN ('open','active','fulfilled','expired')),
  expires_at TIMESTAMPTZ DEFAULT NOW() + INTERVAL '24 hours',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS group_deal_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_deal_id BIGINT REFERENCES group_deals(id) ON DELETE CASCADE,
  telegram_id BIGINT NOT NULL,
  full_name TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  quantity INTEGER DEFAULT 1,
  paid BOOLEAN DEFAULT false,
  joined_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Gift Registries (የስጦታ መዝገብ) ──────────
CREATE TABLE IF NOT EXISTS gift_registries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  couple_name TEXT NOT NULL,
  wedding_date TEXT NOT NULL,
  event_type TEXT DEFAULT 'wedding' CHECK (event_type IN ('wedding','birthday','baby_shower','other')),
  message TEXT DEFAULT '',
  share_token TEXT UNIQUE NOT NULL DEFAULT '',
  creator_telegram_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS registry_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registry_id BIGINT REFERENCES gift_registries(id) ON DELETE CASCADE,
  product_id BIGINT,
  product_name TEXT NOT NULL,
  product_image TEXT DEFAULT '',
  price INTEGER NOT NULL,
  quantity INTEGER DEFAULT 1,
  purchased INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS registry_contributors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registry_item_id BIGINT REFERENCES registry_items(id) ON DELETE CASCADE,
  contributor_name TEXT DEFAULT '',
  contributor_telegram_id BIGINT,
  quantity INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Subscriptions (የደንበኝነት ምርቶች) ────────
CREATE TABLE IF NOT EXISTS subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id BIGINT NOT NULL,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT NOT NULL,
  product_image TEXT DEFAULT '',
  quantity INTEGER DEFAULT 1,
  frequency TEXT DEFAULT 'weekly' CHECK (frequency IN ('daily','weekly','monthly')),
  price INTEGER NOT NULL,
  next_delivery TEXT NOT NULL,
  delivery_address TEXT DEFAULT '',
  delivery_note TEXT DEFAULT '',
  status TEXT DEFAULT 'active' CHECK (status IN ('active','paused','cancelled')),
  total_delivered INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Reseller Tracking ─────────────────────────
-- Uses existing affiliates table + adds referral tracking
CREATE TABLE IF NOT EXISTS referral_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referral_code TEXT NOT NULL,
  product_id BIGINT,
  visitor_telegram_id BIGINT,
  converted BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Photo Reviews Enhancement ─────────────────
-- Extends existing reviews table with verified purchase
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS images JSONB DEFAULT '[]'::jsonb;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS verified_purchase BOOLEAN DEFAULT false;

-- ── Indexes ──────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_gd_token ON group_deals(share_token);
CREATE INDEX IF NOT EXISTS idx_gd_status ON group_deals(status);
CREATE INDEX IF NOT EXISTS idx_gdm_deal ON group_deal_members(group_deal_id);
CREATE INDEX IF NOT EXISTS idx_gr_token ON gift_registries(share_token);
CREATE INDEX IF NOT EXISTS idx_ri_registry ON registry_items(registry_id);
CREATE INDEX IF NOT EXISTS idx_sub_telegram ON subscriptions(telegram_id);
CREATE INDEX IF NOT EXISTS idx_sub_status ON subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_sub_next ON subscriptions(next_delivery);
CREATE INDEX IF NOT EXISTS idx_rc_code ON referral_clicks(referral_code);

-- ── RLS Policies ─────────────────────────────
ALTER TABLE group_deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE group_deal_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE gift_registries ENABLE ROW LEVEL SECURITY;
ALTER TABLE registry_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE registry_contributors ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE referral_clicks ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'group_deals' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON group_deals FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'group_deal_members' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON group_deal_members FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'gift_registries' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON gift_registries FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'registry_items' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON registry_items FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'registry_contributors' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON registry_contributors FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'subscriptions' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON subscriptions FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'referral_clicks' AND policyname = 'public_all') THEN
    CREATE POLICY "public_all" ON referral_clicks FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
