-- ============================================
-- Smart Shop Express — Delivery System
-- Complete Database Schema
-- ============================================

CREATE TABLE IF NOT EXISTS delivery_personnel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id BIGINT UNIQUE,
  full_name_amharic TEXT,
  full_name_latin TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  fayda_id TEXT UNIQUE NOT NULL,
  fayda_id_front_url TEXT NOT NULL,
  fayda_id_back_url TEXT NOT NULL,
  fayda_selfie_url TEXT NOT NULL,
  fayda_verified_at TIMESTAMPTZ,
  fayda_verified_by BIGINT,
  vehicle_type TEXT NOT NULL CHECK (vehicle_type IN ('on_foot', 'bicycle', 'motorcycle', 'bajaj')),
  license_plate TEXT,
  vehicle_photo_url TEXT,
  service_zones JSONB DEFAULT '[]'::jsonb,
  available_hours JSONB DEFAULT '[]'::jsonb,
  available_days JSONB DEFAULT '[]'::jsonb,
  emergency_name TEXT NOT NULL,
  emergency_phone TEXT NOT NULL,
  emergency_relationship TEXT NOT NULL,
  emergency_address TEXT,
  bank_name TEXT,
  bank_account TEXT,
  telebirr_number TEXT,
  status TEXT DEFAULT 'pending_fayda' CHECK (status IN ('pending_fayda','pending_review','approved','suspended','rejected')),
  rejection_reason TEXT,
  rating DECIMAL(2,1) DEFAULT 0,
  total_deliveries INTEGER DEFAULT 0,
  total_earnings INTEGER DEFAULT 0,
  driver_score INTEGER DEFAULT 0,
  driver_tier TEXT DEFAULT 'bronze' CHECK (driver_tier IN ('bronze','silver','gold','platinum')),
  is_online BOOLEAN DEFAULT false,
  current_lat DECIMAL(10,7),
  current_lng DECIMAL(10,7),
  location_updated_at TIMESTAMPTZ,
  agreed_to_terms_at TIMESTAMPTZ,
  otp_verified BOOLEAN DEFAULT false,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  last_active_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT,
  driver_id BIGINT REFERENCES delivery_personnel(id),
  vendor_id BIGINT,
  customer_telegram_id BIGINT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','assigned','accepted','at_vendor','picked_up','in_transit','arrived','delivered','failed','cancelled','returned')),
  item_count INTEGER DEFAULT 0,
  item_count_confirmed_at_vendor INTEGER,
  item_count_confirmed_at_customer INTEGER,
  delivery_pin TEXT,
  pin_verified_at TIMESTAMPTZ,
  no_contact BOOLEAN DEFAULT false,
  dropoff_photo_url TEXT,
  cod_amount INTEGER DEFAULT 0,
  cod_collected BOOLEAN DEFAULT false,
  fee INTEGER DEFAULT 0,
  platform_commission INTEGER DEFAULT 0,
  driver_payout INTEGER DEFAULT 0,
  distance_km DECIMAL(5,2),
  pickup_address TEXT,
  delivery_address TEXT,
  pickup_lat DECIMAL(10,7),
  pickup_lng DECIMAL(10,7),
  delivery_lat DECIMAL(10,7),
  delivery_lng DECIMAL(10,7),
  driver_rating INTEGER CHECK (driver_rating BETWEEN 1 AND 5),
  customer_rating INTEGER CHECK (customer_rating BETWEEN 1 AND 5),
  assigned_at TIMESTAMPTZ,
  accepted_at TIMESTAMPTZ,
  picked_up_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS delivery_zones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  bounds JSONB DEFAULT '{}'::jsonb,
  base_fee INTEGER DEFAULT 25,
  per_km_fee INTEGER DEFAULT 10,
  max_distance_km DECIMAL(4,1) DEFAULT 10,
  active BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS driver_earnings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id BIGINT REFERENCES delivery_personnel(id),
  delivery_id BIGINT REFERENCES deliveries(id),
  amount INTEGER NOT NULL,
  commission INTEGER DEFAULT 0,
  type TEXT DEFAULT 'delivery' CHECK (type IN ('delivery','bonus','withdrawal','adjustment','referral')),
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','paid','cancelled')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS delivery_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delivery_id BIGINT REFERENCES deliveries(id),
  sender_type TEXT NOT NULL CHECK (sender_type IN ('driver','customer','admin')),
  sender_id BIGINT,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dp_status ON delivery_personnel(status);
CREATE INDEX IF NOT EXISTS idx_dp_online ON delivery_personnel(is_online) WHERE is_online = true;
CREATE INDEX IF NOT EXISTS idx_del_status ON deliveries(status);
CREATE INDEX IF NOT EXISTS idx_del_driver ON deliveries(driver_id);
CREATE INDEX IF NOT EXISTS idx_del_order ON deliveries(order_number);
CREATE INDEX IF NOT EXISTS idx_de_driver ON driver_earnings(driver_id);
CREATE INDEX IF NOT EXISTS idx_dm_delivery ON delivery_messages(delivery_id);

INSERT INTO delivery_zones (name, base_fee, per_km_fee, max_distance_km, active) VALUES
  ('Bole', 30, 10, 10, true),
  ('Merkato', 25, 8, 8, true),
  ('Piassa', 25, 8, 8, true),
  ('Summit', 35, 12, 10, true),
  ('Mexico', 25, 8, 8, true),
  ('Kazanchis', 30, 10, 10, true),
  ('CMC', 35, 12, 12, true),
  ('Ayat', 35, 12, 12, true)
ON CONFLICT DO NOTHING;

NOTIFY pgrst, 'reload schema';
